package com.wizards.operations.icontrol.AppletPackage;


/**
* com/wizards/operations/icontrol/AppletPackage/membersHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from icontrol.idl
* Monday, March 12, 2012 7:09:13 PM PDT
*/

abstract public class membersHelper
{
  private static String  _id = "IDL:com/wizards/operations/icontrol/Applet/members:1.0";

  public static void insert (org.omg.CORBA.Any a, com.wizards.operations.icontrol.Member[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.wizards.operations.icontrol.Member[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = com.wizards.operations.icontrol.MemberHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (com.wizards.operations.icontrol.AppletPackage.membersHelper.id (), "members", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.wizards.operations.icontrol.Member[] read (org.omg.CORBA.portable.InputStream istream)
  {
    com.wizards.operations.icontrol.Member value[] = null;
    int _len0 = istream.read_long ();
    value = new com.wizards.operations.icontrol.Member[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = com.wizards.operations.icontrol.MemberHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.wizards.operations.icontrol.Member[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      com.wizards.operations.icontrol.MemberHelper.write (ostream, value[_i0]);
  }

}
