package com.wizards.operations.icontrol;


/**
* com/wizards/operations/icontrol/AppletHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from icontrol.idl
* Monday, March 12, 2012 7:09:13 PM PDT
*/

abstract public class AppletHelper
{
  private static String  _id = "IDL:com/wizards/operations/icontrol/Applet:1.0";

  public static void insert (org.omg.CORBA.Any a, com.wizards.operations.icontrol.Applet that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.wizards.operations.icontrol.Applet extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.wizards.operations.icontrol.AppletHelper.id (), "Applet");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.wizards.operations.icontrol.Applet read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AppletStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.wizards.operations.icontrol.Applet value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.wizards.operations.icontrol.Applet narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.wizards.operations.icontrol.Applet)
      return (com.wizards.operations.icontrol.Applet)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.wizards.operations.icontrol._AppletStub stub = new com.wizards.operations.icontrol._AppletStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static com.wizards.operations.icontrol.Applet unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.wizards.operations.icontrol.Applet)
      return (com.wizards.operations.icontrol.Applet)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.wizards.operations.icontrol._AppletStub stub = new com.wizards.operations.icontrol._AppletStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
