package com.wizards.operations.icontrol;


/**
* com/wizards/operations/icontrol/AppletOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from icontrol.idl
* Monday, March 12, 2012 7:09:13 PM PDT
*/

public interface AppletOperations 
{
} // interface AppletOperations
