package icontrol.poolPackage;


/**
* icontrol/poolPackage/membersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from icontrol.idl
* Wednesday, March 7, 2012 9:53:06 PM PST
*/

public final class membersHolder implements org.omg.CORBA.portable.Streamable
{
  public icontrol.member value[] = null;

  public membersHolder ()
  {
  }

  public membersHolder (icontrol.member[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = icontrol.poolPackage.membersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    icontrol.poolPackage.membersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return icontrol.poolPackage.membersHelper.type ();
  }

}
