package icontrol.poolPackage;


/**
* icontrol/poolPackage/membersHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from icontrol.idl
* Wednesday, March 7, 2012 9:53:06 PM PST
*/

abstract public class membersHelper
{
  private static String  _id = "IDL:icontrol/pool/members:1.0";

  public static void insert (org.omg.CORBA.Any a, icontrol.member[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static icontrol.member[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = icontrol.memberHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (icontrol.poolPackage.membersHelper.id (), "members", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static icontrol.member[] read (org.omg.CORBA.portable.InputStream istream)
  {
    icontrol.member value[] = null;
    int _len0 = istream.read_long ();
    value = new icontrol.member[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = icontrol.memberHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, icontrol.member[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      icontrol.memberHelper.write (ostream, value[_i0]);
  }

}
