module com {
module wizards {
module operations {
module icontrol {

  struct Member {
    string name;
	long long connections;
	string availability;
	string enabled;
	string description;
  };
  
  interface Applet {
	typedef sequence<Member> members;
  };
  
  interface Pool {
    typedef sequence<Member> members;
	void startPush(in string poolName);
	void disablePoolMember(in string memberName);
	void enablePoolMember(in string memberName);
  };
}; }; }; };