package icontrol;

/**
* icontrol/memberHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from icontrol.idl
* Wednesday, March 7, 2012 9:53:06 PM PST
*/

public final class memberHolder implements org.omg.CORBA.portable.Streamable
{
  public icontrol.member value = null;

  public memberHolder ()
  {
  }

  public memberHolder (icontrol.member initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = icontrol.memberHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    icontrol.memberHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return icontrol.memberHelper.type ();
  }

}
