package icontrol;


/**
* icontrol/poolOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from icontrol.idl
* Wednesday, March 7, 2012 9:53:06 PM PST
*/

public interface poolOperations 
{
  String name ();
  void getMembers (String poolName, icontrol.memberHolder members);
  void disablePoolMember (String poolName, String memberName);
  void enablePoolMember (String poolName, String memberName);
} // interface poolOperations
