package icontrol;


/**
* icontrol/pool.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from icontrol.idl
* Wednesday, March 7, 2012 9:53:06 PM PST
*/

public interface pool extends poolOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface pool
