package icontrol;

/**
* icontrol/poolHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from icontrol.idl
* Wednesday, March 7, 2012 9:53:06 PM PST
*/

public final class poolHolder implements org.omg.CORBA.portable.Streamable
{
  public icontrol.pool value = null;

  public poolHolder ()
  {
  }

  public poolHolder (icontrol.pool initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = icontrol.poolHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    icontrol.poolHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return icontrol.poolHelper.type ();
  }

}
