package icontrol;


/**
* icontrol/poolHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from icontrol.idl
* Wednesday, March 7, 2012 9:53:06 PM PST
*/

abstract public class poolHelper
{
  private static String  _id = "IDL:icontrol/pool:1.0";

  public static void insert (org.omg.CORBA.Any a, icontrol.pool that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static icontrol.pool extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (icontrol.poolHelper.id (), "pool");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static icontrol.pool read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_poolStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, icontrol.pool value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static icontrol.pool narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof icontrol.pool)
      return (icontrol.pool)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      icontrol._poolStub stub = new icontrol._poolStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static icontrol.pool unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof icontrol.pool)
      return (icontrol.pool)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      icontrol._poolStub stub = new icontrol._poolStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
