package com.wizards.operations.icontrol;

/**
* com/wizards/operations/icontrol/AppletHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from icontrol.idl
* Monday, March 12, 2012 7:09:13 PM PDT
*/

public final class AppletHolder implements org.omg.CORBA.portable.Streamable
{
  public com.wizards.operations.icontrol.Applet value = null;

  public AppletHolder ()
  {
  }

  public AppletHolder (com.wizards.operations.icontrol.Applet initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.wizards.operations.icontrol.AppletHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.wizards.operations.icontrol.AppletHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.wizards.operations.icontrol.AppletHelper.type ();
  }

}
