package com.wizards.operations.icontrol;


/**
* com/wizards/operations/icontrol/Applet.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from icontrol.idl
* Monday, March 12, 2012 7:09:13 PM PDT
*/

public interface Applet extends AppletOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Applet
