package com.wizards.operations.icontrol;

/**
* com/wizards/operations/icontrol/MemberHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from icontrol.idl
* Monday, March 12, 2012 7:09:13 PM PDT
*/

public final class MemberHolder implements org.omg.CORBA.portable.Streamable
{
  public com.wizards.operations.icontrol.Member value = null;

  public MemberHolder ()
  {
  }

  public MemberHolder (com.wizards.operations.icontrol.Member initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.wizards.operations.icontrol.MemberHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.wizards.operations.icontrol.MemberHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.wizards.operations.icontrol.MemberHelper.type ();
  }

}
