package com.wizards.operations.icontrol;


/**
* com/wizards/operations/icontrol/Member.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from icontrol.idl
* Monday, March 12, 2012 7:09:13 PM PDT
*/

public final class Member implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public long connections = (long)0;
  public String availability = null;
  public String enabled = null;
  public String description = null;

  public Member ()
  {
  } // ctor

  public Member (String _name, long _connections, String _availability, String _enabled, String _description)
  {
    name = _name;
    connections = _connections;
    availability = _availability;
    enabled = _enabled;
    description = _description;
  } // ctor

} // class Member
