package com.wizards.operations.icontrol;


/**
* com/wizards/operations/icontrol/Pool.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from icontrol.idl
* Monday, March 12, 2012 7:09:13 PM PDT
*/

public interface Pool extends PoolOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Pool
