package com.wizards.operations.icontrol;


/**
* com/wizards/operations/icontrol/PoolPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from icontrol.idl
* Monday, March 12, 2012 7:09:13 PM PDT
*/

public abstract class PoolPOA extends org.omg.PortableServer.Servant
 implements com.wizards.operations.icontrol.PoolOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("startPush", new java.lang.Integer (0));
    _methods.put ("disablePoolMember", new java.lang.Integer (1));
    _methods.put ("enablePoolMember", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // com/wizards/operations/icontrol/Pool/startPush
       {
         String poolName = in.read_string ();
         this.startPush (poolName);
         out = $rh.createReply();
         break;
       }

       case 1:  // com/wizards/operations/icontrol/Pool/disablePoolMember
       {
         String memberName = in.read_string ();
         this.disablePoolMember (memberName);
         out = $rh.createReply();
         break;
       }

       case 2:  // com/wizards/operations/icontrol/Pool/enablePoolMember
       {
         String memberName = in.read_string ();
         this.enablePoolMember (memberName);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:com/wizards/operations/icontrol/Pool:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Pool _this() 
  {
    return PoolHelper.narrow(
    super._this_object());
  }

  public Pool _this(org.omg.CORBA.ORB orb) 
  {
    return PoolHelper.narrow(
    super._this_object(orb));
  }


} // class PoolPOA
