package com.wizards.operations.icontrol.AppletPackage;


/**
* com/wizards/operations/icontrol/AppletPackage/membersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from icontrol.idl
* Monday, March 12, 2012 7:09:13 PM PDT
*/

public final class membersHolder implements org.omg.CORBA.portable.Streamable
{
  public com.wizards.operations.icontrol.Member value[] = null;

  public membersHolder ()
  {
  }

  public membersHolder (com.wizards.operations.icontrol.Member[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.wizards.operations.icontrol.AppletPackage.membersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.wizards.operations.icontrol.AppletPackage.membersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.wizards.operations.icontrol.AppletPackage.membersHelper.type ();
  }

}
